version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.11
    commands:
      - echo "Installing Docker Compose..."
      - pip install docker-compose
      - docker-compose --version
      - echo "Starting Docker..."
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo "Logging in to Docker Hub (if required)..."
      # - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD  # Uncomment if you're pushing images to Docker Hub
  build:
    commands:
      - echo "Building Docker images..."
      - docker-compose build
      # - docker-compose push  # Uncomment if you're pushing images to Docker Hub
  post_build:
    commands:
      - echo "Run any post-build steps here..."
      - echo "$DEPLOY_KEY" > deploy_key.pem
      - chmod 600 deploy_key.pem
      - ssh -o StrictHostKeyChecking=no -i deploy_key.pem ec2-user@$EC2_HOST "cd /path/to/your/repo && git pull && docker-compose up --build -d"

artifacts:
  files: 
    - '**/*'
