version: 0.2

phases:
  pre_build:
    commands:
      - echo "Fetching the latest code from the repository..."
      - git pull
  build:
    commands:
      - echo "Building Docker images using docker-compose..."
      - docker-compose build

artifacts:
  files: 
    - '**/*'
