version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-service
      - booking-service
      - ship-service
      - planet-service

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URI: amqp://rabbitmq:5672

  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URI: amqp://rabbitmq:5672

  ship-service:
    build:
      context: ./ship-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URI: amqp://rabbitmq:5672

  planet-service:
    build:
      context: ./planet-service
      dockerfile: Dockerfile

  rabbitmq:
    image: "rabbitmq"
    ports:
      - "15672:15672"  # Management UI (optional)
      - "5672:5672"    # Default RabbitMQ broker port
